### ISSUE TITLE
Camera glitching

### ISSUE THREAD

**Issue by paralin** [hendrikp/Plugin_Camera#2]
The camera seems to be glitching into the terrain with collision enabled, and with it disabled, the min and max pitch is not working, and the camera orbits the character strangely. Also, the weapon doesn't actually aim at the middle of the view - it seems to be off a bit, and not rotate immediately when the camera is rotated.

**Comment by hendrikp** [comment]
Yep some of those are know bugs, as written in the release notes this is an experimental release. For the Aiming there is an aimfix parameter you can activate it if you prefer it that way.

There is too much divergent requirements for such kind of plugin, so see this here more as a sample you can expand. I'm not going to try an all-embracing approach here. (At least not at this point)

Looking forward to your contributions, in fact I'm searching for someone to take this plugin over.
